name: Build Docs
description: Build Storybook docs
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: yarn
    - run: yarn install --immutable
      shell: bash
    - run: yarn build:docs
      shell: bash
