compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnpm

npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: .yarn/releases/yarn-4.12.0.cjs

plugins:
  - .yarn/plugins/plugin-husky.cjs
