compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnpm

npmAuthToken: "${NPM_TOKEN}"

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.9.4.cjs
