approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnpm

npmMinimalAgeGate: 7d

npmRegistryServer: 'https://npm.pkg.reapitaccess.com/'

plugins:
  - .yarn/plugins/plugin-husky.cjs

yarnPath: .yarn/releases/yarn-4.16.0.cjs
