name: Check
description: Run type-checking and linting
runs:
  using: composite
  steps:
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 24
        cache: yarn
    - run: yarn install --immutable
      shell: bash
    - run: yarn check
      shell: bash
