import manifestData from "./manifest.json" with { type: "json" };

// Type definitions for the manifest
export interface CodemodMetadata {
  readonly name: string;
  readonly description: string | null;
}

// CodemodName is inferred from manifest.json: no manual list to maintain.
// manifest.json is generated by `yarn build:codemods:manifest`, which discovers
// codemods from the filesystem, so the type stays in sync automatically.
export type CodemodName = (typeof manifestData.codemods)[number]["name"];
export const CODEMOD_NAMES: readonly CodemodName[] = manifestData.codemods.map(
  (c) => c.name,
) as CodemodName[];

export const AVAILABLE_CODEMODS: readonly CodemodMetadata[] = manifestData.codemods;

/**
 * Returns available codemods from the generated manifest.
 *
 * @returns Array of codemod names
 */
export function listCodemods(): string[] {
  return CODEMOD_NAMES.slice(); // Return copy to prevent mutation
}

/**
 * Retrieves the description from the manifest for a specific codemod.
 *
 * @param name - The codemod name
 * @returns The description, or null if not found
 */
export function getCodemodDescription(name: string): string | null {
  const metadata = AVAILABLE_CODEMODS.find((c) => c.name === name);
  return metadata?.description ?? null;
}

/**
 * Type guard that validates a codemod name exists in the manifest.
 * Use this to narrow a `string` to `CodemodName` before using it as a key.
 *
 * @param name - The codemod name to validate
 * @returns true if the name is a valid CodemodName, false otherwise
 */
export function validateCodemodName(name: string): name is CodemodName {
  return CODEMOD_NAMES.includes(name as CodemodName);
}
