import * as esbuild from 'esbuild'
import { globSync } from 'node:fs'
import path from 'node:path'

/**
 * Build script for codemods CLI.
 *
 * Uses esbuild to bundle the codemods CLI with all dependencies (including ts-morph)
 * to create a self-contained executable that can be distributed via npm.
 *
 * Entry points:
 * - bin.ts: Main CLI entry point (pulls in transforms.ts transitively)
 * - <codemod>/transform.ts: Individual codemod transforms (dynamically discovered)
 *
 * transforms.ts is generated by `yarn build:codemods:manifest` and is pulled in
 * as a dependency of bin.ts — it does not need to be listed as an entry point.
 */

async function build() {
  console.log('Building codemods CLI with esbuild...\n')

  // Discover all transform files
  const transformFiles = globSync('codemods/*/transform.ts')

  const transformEntryPoints = Object.fromEntries(
    transformFiles.map((filePath) => {
      const codemodName = path.basename(path.dirname(filePath))
      return [
        `${codemodName}/transform`, // Output: dist/codemods/{name}/transform.js
        filePath, // Input: codemods/{name}/transform.ts
      ]
    }),
  )

  const entryPoints = {
    bin: 'codemods/bin.ts',
    codemods: 'codemods/codemods.ts',
    runner: 'codemods/runner.ts',
    ...transformEntryPoints,
  }

  console.log('Entry points:')
  Object.entries(entryPoints).forEach(([name, file]) => {
    console.log(`  ${name}: ${file}`)
  })
  console.log()

  try {
    await esbuild.build({
      entryPoints,
      bundle: true,
      platform: 'node',
      target: 'node22',
      format: 'esm',
      outdir: 'dist/codemods',
      outExtension: { '.js': '.js' },
      // Inject polyfills for CommonJS globals that bundled dependencies expect
      banner: {
        js: [
          `import { createRequire } from 'module';`,
          `import { fileURLToPath } from 'url';`,
          `import { dirname } from 'path';`,
          `const require = createRequire(import.meta.url);`,
          `const __filename = fileURLToPath(import.meta.url);`,
          `const __dirname = dirname(__filename);`,
        ].join('\n'),
      },
      // No minification for easier debugging
      minify: false,
      // No source maps to keep bundle size smaller
      sourcemap: false,
      // Keep readable code
      keepNames: true,
    })

    console.log('✓ Build completed successfully!\n')
    console.log('Output: dist/codemods/')
  } catch (error) {
    console.error('✗ Build failed:', error)
    process.exit(1)
  }
}

build()
