import type { Transform } from './runner.js'

// Generated by generate-manifest.ts — do not edit manually.
// Run `yarn build:codemods:manifest` to regenerate.
export const transforms = {
  "apply-textarea-field-sizing": () => import("./apply-textarea-field-sizing/transform.js"),
  "at-a-glance-article-card": () => import("./at-a-glance-article-card/transform.js"),
  "rewrite-text-font-imports": () => import("./rewrite-text-font-imports/transform.js"),
  "rewrite-v4-imports": () => import("./rewrite-v4-imports/transform.js"),
  "rewrite-v5-imports": () => import("./rewrite-v5-imports/transform.js"),
  "upgrade-css-variables": () => import("./upgrade-css-variables/transform.js"),
  "upgrade-deprecated-button": () => import("./upgrade-deprecated-button/transform.js"),
  "upgrade-deprecated-icon": () => import("./upgrade-deprecated-icon/transform.js"),
  "upgrade-deprecated-use-media-query": () => import("./upgrade-deprecated-use-media-query/transform.js"),
} satisfies Record<string, () => Promise<{ default: Transform }>>
