import type { Transform } from './runner.js'

// Generated by generate-manifest.ts — do not edit manually.
// Run `yarn build:codemods:manifest` to regenerate.
export const transforms = {
  "apply-textarea-field-sizing": () => import("./apply-textarea-field-sizing/transform.js"),
  "at-a-glance-article-card": () => import("./at-a-glance-article-card/transform.js"),
  "rename-empty-data": () => import("./rename-empty-data/transform.js"),
  "replace-deprecated-label": () => import("./replace-deprecated-label/transform.js"),
  "replace-deprecated-pagination": () => import("./replace-deprecated-pagination/transform.js"),
  "replace-deprecated-snack": () => import("./replace-deprecated-snack/transform.js"),
  "replace-deprecated-toggle": () => import("./replace-deprecated-toggle/transform.js"),
  "replace-deprecated-toggle-radio": () => import("./replace-deprecated-toggle-radio/transform.js"),
  "replace-deprecated-use-click-outside": () => import("./replace-deprecated-use-click-outside/transform.js"),
  "replace-lab-mobile-nav-item": () => import("./replace-lab-mobile-nav-item/transform.js"),
  "replace-lab-radio": () => import("./replace-lab-radio/transform.js"),
  "replace-lab-radio-group": () => import("./replace-lab-radio-group/transform.js"),
  "replace-lab-search-input": () => import("./replace-lab-search-input/transform.js"),
  "replace-lab-table": () => import("./replace-lab-table/transform.js"),
  "rewrite-anz-app-switcher-imports": () => import("./rewrite-anz-app-switcher-imports/transform.js"),
  "rewrite-combobox-imports": () => import("./rewrite-combobox-imports/transform.js"),
  "rewrite-text-font-imports": () => import("./rewrite-text-font-imports/transform.js"),
  "rewrite-v4-imports": () => import("./rewrite-v4-imports/transform.js"),
  "rewrite-v5-imports": () => import("./rewrite-v5-imports/transform.js"),
  "upgrade-css-variables": () => import("./upgrade-css-variables/transform.js"),
  "upgrade-deprecated-badge": () => import("./upgrade-deprecated-badge/transform.js"),
  "upgrade-deprecated-button": () => import("./upgrade-deprecated-button/transform.js"),
  "upgrade-deprecated-button-group": () => import("./upgrade-deprecated-button-group/transform.js"),
  "upgrade-deprecated-icon": () => import("./upgrade-deprecated-icon/transform.js"),
  "upgrade-deprecated-split-button": () => import("./upgrade-deprecated-split-button/transform.js"),
  "upgrade-deprecated-tag": () => import("./upgrade-deprecated-tag/transform.js"),
  "upgrade-deprecated-use-media-query": () => import("./upgrade-deprecated-use-media-query/transform.js"),
} satisfies Record<string, () => Promise<{ default: Transform }>>
