#!/bin/sh
[ "$CI" = "true" ] && exit 0
# In a post-checkout hook, git passes three arguments:
#   $1 - previous HEAD (the ref you were on)
#   $2 - new HEAD (the ref you've switched to)
#   $3 - 1 if it was a branch checkout, 0 if it was a file checkout (e.g. git checkout -- src/foo.ts)
# Skip yarn install for file checkouts.
[ "$3" = "0" ] && exit 0
yarn install
