name: Figma Code Connect

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.figma.tsx'
      - 'figma.config.json'

env:
  CI: true

jobs:
  publish-code-connect:
    name: Publish Code Connect
    runs-on:
      group: rpt-gbl-linux-x64
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install
        run: yarn install --immutable

      - name: Publish to Figma
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
        run: yarn figma connect publish --exit-on-unreadable-files
