name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

env:
  CI: true

jobs:
  release:
    name: Release
    runs-on:
      group: rpt-gbl-linux-x64
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: Generate app token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'

      - name: Install
        run: yarn install --immutable

      - name: Check
        run: yarn check

      - name: Test
        run: yarn test run --passWithNoTests

      - name: Build
        run: yarn build:types && yarn build:lib && yarn build:codemods

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          version: yarn changeset version
          publish: yarn changeset publish
          title: 'chore: version packages'
          commit: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload npm debug logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: npm-debug-logs
          path: ~/.npm/_logs/

  deploy-storybook-prod:
    name: Deploy Storybook (Prod)
    needs: release
    if: needs.release.outputs.published == 'true'
    uses: ./.github/workflows/deploy-storybook-prod.yml
    secrets: inherit
