name: Release Beta

on:
  push:
    branches:
      - beta

permissions:
  contents: read
  id-token: write

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  CI: true
  APP_STAGE: 'development'

jobs:
  release-beta:
    name: Release Beta
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ARN_DEV }}
          role-session-name: AWS_OIDC_ARN_DEV
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install
        run: yarn

      - name: Build Storybook
        run: |
          yarn build:storybook

      - name: Deploy
        run: |
          yarn deploy
