name: Release Prod

on:
  release:
    types: [published]

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  CI: true
  IS_RELEASE: true
  APP_STAGE: 'production'

permissions:
  contents: write
  id-token: write

jobs:
  release-prod:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ARN_PROD }}
          role-session-name: AWS_OIDC_ARN_PROD
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Get Tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: '(?<package>.*)_(?<version>.*)'

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set Version
        run: |
          echo "RELEASE_VERSION=${{ steps.tagName.outputs.package }}_${{ steps.tagName.outputs.version }}" >> $GITHUB_ENV

      - name: Install
        run: yarn

      - name: Lint
        run: |
          yarn lint

      - name: TypeCheck
        run: |
          yarn check

      - name: Test
        run: |
          yarn test --watch=false --ci --forceExit --detectOpenHandles --runInBand --passWithNoTests

      - name: Build Lib
        run: |
          yarn build:dist

      - name: Build Storybook
        run: |
          yarn build:storybook

      - name: Package Version Bump
        run: |
          yarn version ${{ steps.tagName.outputs.version }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: bump version to ${{ steps.tagName.outputs.version }}'
          branch: main

      - name: Deploy
        run: |
          yarn deploy

      - name: Publish
        run: |
          yarn publish --tag latest
